### ISSUE TITLE
error when running with a config file

### ISSUE THREAD

**Issue by guest951** [ornicar/lila-ws#215]
I'm trying to run the server with a config file, but even if use the same config file as in the readme, when I do `sbt run -Dconfig.file=my.conf` I get this error:
```
[error] (run-main-0) com.typesafe.config.ConfigException$Missing: merge of system properties,my.conf: 1,reference.conf @ jar:file:/mnt/d/github/lila-ws/target/bg-jobs/sbt_d0fd6c7b/target/454908f7/caebe80d/akka-actor-typed_2.13-2.6.15.jar!/reference.conf: 1,reference.conf @ jar:file:/mnt/d/github/lila-ws/target/bg-jobs/sbt_d0fd6c7b/target/0cf4da2e/ae2d481e/kamon-core_2.13-2.2.1.jar!/reference.conf: 1,reference.conf @ jar:file:/mnt/d/github/lila-ws/target/bg-jobs/sbt_d0fd6c7b/target/d2c2698a/f43337f6/kamon-influxdb_2.13-2.2.1.jar!/reference.conf: 1,reference.conf @ jar:file:/mnt/d/github/lila-ws/target/bg-jobs/sbt_d0fd6c7b/target/d1d9b9b5/ebf92e9a/kamon-system-metrics_2.13-2.2.1.jar!/reference.conf: 1,reference.conf @ jar:file:/mnt/d/github/lila-ws/target/bg-jobs/sbt_d0fd6c7b/target/5fdf4126/5ff27aca/akka-actor_2.13-2.6.15.jar!/reference.conf: 1: No configuration setting found for key 'reactivemongo'
[error] com.typesafe.config.ConfigException$Missing: merge of system properties,my.conf: 1,reference.conf @ jar:file:/mnt/d/github/lila-ws/target/bg-jobs/sbt_d0fd6c7b/target/454908f7/caebe80d/akka-actor-typed_2.13-2.6.15.jar!/reference.conf: 1,reference.conf @ jar:file:/mnt/d/github/lila-ws/target/bg-jobs/sbt_d0fd6c7b/target/0cf4da2e/ae2d481e/kamon-core_2.13-2.2.1.jar!/reference.conf: 1,reference.conf @ jar:file:/mnt/d/github/lila-ws/target/bg-jobs/sbt_d0fd6c7b/target/d2c2698a/f43337f6/kamon-influxdb_2.13-2.2.1.jar!/reference.conf: 1,reference.conf @ jar:file:/mnt/d/github/lila-ws/target/bg-jobs/sbt_d0fd6c7b/target/d1d9b9b5/ebf92e9a/kamon-system-metrics_2.13-2.2.1.jar!/reference.conf: 1,reference.conf @ jar:file:/mnt/d/github/lila-ws/target/bg-jobs/sbt_d0fd6c7b/target/5fdf4126/5ff27aca/akka-actor_2.13-2.6.15.jar!/reference.conf: 1: No configuration setting found for key 'reactivemongo'
[error]         at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
[error]         at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
[error]         at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
[error]         at com.typesafe.config.impl.SimpleConfig.getObject(SimpleConfig.java:268)
[error]         at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:274)
[error]         at com.typesafe.config.impl.SimpleConfig.getConfig(SimpleConfig.java:41)
[error]         at lila.ws.Mongo.<init>(Mongo.scala:17)
[error]         at lila.ws.Boot$.mongo$lzycompute(LilaWsServer.scala:19)
[error]         at lila.ws.Boot$.mongo(LilaWsServer.scala:19)
[error]         at lila.ws.Boot$.controller$lzycompute(LilaWsServer.scala:34)
[error]         at lila.ws.Boot$.controller(LilaWsServer.scala:34)
[error]         at lila.ws.Boot$.router$lzycompute(LilaWsServer.scala:35)
[error]         at lila.ws.Boot$.router(LilaWsServer.scala:35)
[error]         at lila.ws.Boot$.nettyServer$lzycompute(LilaWsServer.scala:38)
[error]         at lila.ws.Boot$.router(LilaWsServer.scala:35)
[error]         at lila.ws.Boot$.nettyServer$lzycompute(LilaWsServer.scala:38)
[error]         at lila.ws.Boot$.nettyServer(LilaWsServer.scala:38)
[error]         at lila.ws.Boot$.delayedEndpoint$lila$ws$Boot$1(LilaWsServer.scala:41)
[error]         at lila.ws.Boot$delayedInit$body.apply(LilaWsServer.scala:12)
[error]         at scala.Function0.apply$mcV$sp(Function0.scala:39)
[error]         at scala.Function0.apply$mcV$sp$(Function0.scala:39)
[error]         at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:17)
[error]         at scala.App.$anonfun$main$1(App.scala:76)
[error]         at scala.App.$anonfun$main$1$adapted(App.scala:76)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:919)
[error]         at scala.App.main(App.scala:76)
[error]         at scala.App.main$(App.scala:74)
[error]         at lila.ws.Boot$.main(LilaWsServer.scala:12)
[error]         at lila.ws.Boot.main(LilaWsServer.scala)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[error] stack trace is suppressed; run last Compile / bgRun for the full output
```
I don't know exactly what to put for the key `reactivemongo`. It seems it needs to be an object but I don't know more.

**Comment by niklasf** [comment]
Use `include "application"` in your custom config to include all the default values from https://github.com/ornicar/lila-ws/blob/master/src/main/resources/application.conf.

**Comment by guest951** [comment]
Thanks, it was already the case but for this to work the config file has to be in the folder `src/main/resources`, this detail doesn't appear in the readme.

**Comment by niklasf** [comment]
Mhh ... that shouldn't be the case.
